// All the events that will be used

#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq)]
pub enum Event {
    EvReaderNewItem,
    EvReaderFinished,
    EvMatcherNewItem,
    EvMatcherResetQuery,
    EvMatcherUpdateProcess,
    EvMatcherStart,
    EvMatcherStartReceived,
    EvMatcherEnd,
    EvQueryChange,
    EvInputKey,
    EvInputInvalid,
    EvResize,

    EvActAddChar,

    // user bind actions
    EvActAbort,
    EvActAccept,
    EvActBackwardChar,
    EvActBackwardDeleteChar,
    EvActBackwardKillWord,
    EvActBackwardWord,
    EvActBeginningOfLine,
    EvActCancel,
    EvActClearScreen,
    EvActDeleteChar,
    EvActDeleteCharEOF,
    EvActDeselectAll,
    EvActDown,
    EvActEndOfLine,
    EvActForwardChar,
    EvActForwardWord,
    EvActIgnore,
    EvActKillLine,
    EvActKillWord,
    EvActNextHistory,
    EvActPageDown,
    EvActPageUp,
    EvActPreviousHistory,
    EvActSelectAll,
    EvActToggle,
    EvActToggleAll,
    EvActToggleDown,
    EvActToggleIn,
    EvActToggleOut,
    EvActToggleSort,
    EvActToggleUp,
    EvActUnixLineDiscard,
    EvActUnixWordRubout,
    EvActUp,
    EvActYank,
}
