// All the events that will be used

use std::any::Any;

pub type EventArg = Box<Any + 'static + Send>;

#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq)]
pub enum Event {
    EvReaderRestart,
    EvReaderEnd,
    EvMatcherRestart,
    EvModelRestart,
    EvActRedraw,
    EvModelRedraw,
    EvModelNewItem,

    EvReaderNewItem,
    EvReaderResetQuery,
    EvReaderSync,
    EvMatcherNewItem,
    EvMatcherResetQuery,
    EvMatcherUpdateProcess,
    EvMatcherEnd,
    EvMatcherSync,
    EvModelAck,
    EvQueryChange,
    EvInputKey,
    EvInputInvalid,
    EvResize,

    EvActAddChar,

    // user bind actions
    EvActAbort,
    EvActAccept,
    EvActBackwardChar,
    EvActBackwardDeleteChar,
    EvActBackwardKillWord,
    EvActBackwardWord,
    EvActBeginningOfLine,
    EvActCancel,
    EvActClearScreen,
    EvActDeleteChar,
    EvActDeleteCharEOF,
    EvActDeselectAll,
    EvActDown,
    EvActEndOfLine,
    EvActForwardChar,
    EvActForwardWord,
    EvActIgnore,
    EvActKillLine,
    EvActKillWord,
    EvActNextHistory,
    EvActPageDown,
    EvActPageUp,
    EvActPreviousHistory,
    EvActRotateMode,
    EvActScrollLeft,
    EvActScrollRight,
    EvActSelectAll,
    EvActToggle,
    EvActToggleAll,
    EvActToggleDown,
    EvActToggleIn,
    EvActToggleOut,
    EvActToggleSort,
    EvActToggleUp,
    EvActUnixLineDiscard,
    EvActUnixWordRubout,
    EvActUp,
    EvActYank,
}

pub fn parse_action(action: &str) -> Option<Event> {
    match action {
        "abort"                =>   Some(Event::EvActAbort),
        "accept"               =>   Some(Event::EvActAccept),
        "backward-char"        =>   Some(Event::EvActBackwardChar),
        "backward-delete-char" =>   Some(Event::EvActBackwardDeleteChar),
        "backward-kill-word"   =>   Some(Event::EvActBackwardKillWord),
        "backward-word"        =>   Some(Event::EvActBackwardWord),
        "beginning-of-line"    =>   Some(Event::EvActBeginningOfLine),
        "cancel"               =>   Some(Event::EvActCancel),
        "clear-screen"         =>   Some(Event::EvActClearScreen),
        "delete-char"          =>   Some(Event::EvActDeleteChar),
        "delete-charEOF"       =>   Some(Event::EvActDeleteCharEOF),
        "deselect-all"         =>   Some(Event::EvActDeselectAll),
        "down"                 =>   Some(Event::EvActDown),
        "end-of-line"          =>   Some(Event::EvActEndOfLine),
        "forward-char"         =>   Some(Event::EvActForwardChar),
        "forward-word"         =>   Some(Event::EvActForwardWord),
        "ignore"               =>   Some(Event::EvActIgnore),
        "kill-line"            =>   Some(Event::EvActKillLine),
        "kill-word"            =>   Some(Event::EvActKillWord),
        "next-history"         =>   Some(Event::EvActNextHistory),
        "page-down"            =>   Some(Event::EvActPageDown),
        "page-up"              =>   Some(Event::EvActPageUp),
        "previous-history"     =>   Some(Event::EvActPreviousHistory),
        "scroll-left"          =>   Some(Event::EvActScrollLeft),
        "scroll-right"         =>   Some(Event::EvActScrollRight),
        "select-all"           =>   Some(Event::EvActSelectAll),
        "toggle"               =>   Some(Event::EvActToggle),
        "toggle-all"           =>   Some(Event::EvActToggleAll),
        "toggle-down"          =>   Some(Event::EvActToggleDown),
        "toggle-in"            =>   Some(Event::EvActToggleIn),
        "toggle-out"           =>   Some(Event::EvActToggleOut),
        "toggle-sort"          =>   Some(Event::EvActToggleSort),
        "toggle-up"            =>   Some(Event::EvActToggleUp),
        "unix-line-discard"    =>   Some(Event::EvActUnixLineDiscard),
        "unix-word-rubout"     =>   Some(Event::EvActUnixWordRubout),
        "up"                   =>   Some(Event::EvActUp),
        "yank"                 =>   Some(Event::EvActYank),
        _ => None
    }
}
